### ISSUE TITLE
Compiled scripts throw errors

### ISSUE THREAD

**Issue by SurferLancelot** [MScholtes/Win-PS2EXE#2]
Hi,

Great app BTW use it all the time but I have noticed that I seem to get a lot of issues when I have compiled my scripts mostly around the invoke-command cmdlets when executing on remote systems.

This is great for basic powershell GUI's / Scripts but once they get more in depth it will throw errors where there were none before when executing the ps1 files.

I also noticed some issues around the Try{} Catch{} when doing error handling. 

Is this something i'm doing wrong? any info would be appreciated thanks.

Kind Regards
Surfer

**Comment by MScholtes** [comment]
Hello SurferLancelot, 

I would like to help you with your problems, but your descriptions are sort of unclear. I need some informations to do investigate:

- What issues do you have when executing on remote systems? Do you have an example? How are you executing remote, with the -ComputerName of the Invoke-Command parameter?

- What are you doing "in depth" that leads to errors? What errors?

- What issues do you have with try{} catch{} ?

Greetings

Markus

**Comment by MScholtes** [comment]
Hello @SurferLancelot,
since there is no response to my request for information, I assume that the issues are solved and I close the request.

Greetings

Markus
