### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by ghost** [MScholtes/Win-PS2EXE#6]
<h1>Impossible to compile</h1>
<p>
There is an error in the *.cs file.
<br />
When compiling, it shows an error.
</p>

**Comment by MScholtes** [comment]
Hello Edward,

that is a pity. What happens and what is the error message?

Greetings

Markus

**Comment by ghost** [comment]
<h1>Check it?</h1>
<p>Wanna check it again?</p>

**Comment by MScholtes** [comment]
Hello Edward,

the compilation succeeds without error for me. Please name the error message, without it I can't help you.

**Comment by ghost** [comment]
> Hello Edward,
> 
> the compilation succeeds without error for me. Please name the error message, without it I can't help you.

Well the error is with the Microsoft .NET Framework.
That is the error.

**Comment by MScholtes** [comment]
The issuer seems to have no interest in a solution. Since he is not cooperating (he does not provide the necessary information), I am closing the case.
