### ISSUE TITLE
How can I use this as a dll?

### ISSUE THREAD

**Issue by itaysarig** [MScholtes/Win-PS2EXE#7]
I want to use ps2exe as part as my code and call a method to do it instead of my current solution.
Currently what I've done was to compile ps2exe.ps1 using itself, allowing me to use that exe to compile other PowerShell scripts.
I have a software which uses it, I write down a piece of PowerShell code during runtime and I compile it to an exe.
The issue I currently have is when I use the start process method to actually use it, I have some issues with.

**Comment by MScholtes** [comment]
Hello itaysarig,

I do not plan to make a DLL version of _PS2EXE_. Your request is the first and there are some weird issues implementing an interface.

You may do it by yourself by compiling _ps2exe_ with itself using the parameter **-prepareDebug** (**-debug** in older versions). This will result in a file _ps2exe.cs_ you can rework to an dll source file and then compile.

Greetings

Markus

**Comment by itaysarig** [comment]
Thanks
