### ISSUE TITLE
Win-PS2exe

### ISSUE THREAD

**Issue by pbarnes21** [MScholtes/Win-PS2EXE#8]
Great program but need the compiled exe to work across the Windows platform regardless of the .Net version without having to recompile the powershell script for each variance.  Is there an update that will do that or is that not possible?

**Comment by MScholtes** [comment]
Hello @pbarnes21,

every supported version of Windows has .Net 4 installed. So the .Net 4 version of **Win-PS2EXE** should work everywhere.

If you really have some old systems with only .Net 3.5 installed I think you might get it to work with the .Net 3.5 version of **Win-PS2EXE** and a config file named **Win-PS2EXE.exe.config** in the same directory with the following content:
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
	<startup>
		<supportedRuntime version="v2.0.50727"/>
		<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/>
	</startup>
</configuration>
```

This should work with every .Net 3.5 and .Net 4 combination. But no guarantee!

Greetings

Markus

**Comment by pbarnes21** [comment]
I originally created the exe on Windows7 SP1 with .Net 4.5.2 (didn't have all the updates to Windows on it) but then when trying to run it on Windows10 SHB with .Net 4.8 it failed to run and I get the KERNALBASE.DLL error.  Tried creating the exe on the Window10 SHB with .Net 4.8 and running it on my Windows7 SP1 with .Net 4.5.2, and then all the way up to .Net 4.8, and it failed to run throwing a KERNALBASE.DLL error there so the only way I can get the exe to run is to create it on the machine that I'm running it on but that's not good because I need to put the exe out to a variety of Windows environment and have it run.  I even tried the compatibility mode options before running it but that didn't work either.  See attached file with the two errors Windows generated in the Application Event Log.  
[Windows_Application_Errors with Win-PS2exe.txt](https://github.com/MScholtes/Win-PS2EXE/files/7008450/Windows_Application_Errors.with.Win-PS2exe.txt)
Any additional information you can give me would be much appreciated!

**Comment by MScholtes** [comment]
Hello @pbarnes21,

obviously I misunderstood your question, as you asked it in the Win-PS2EXE repository and not PS2EXE repository.

Your problem is probably not with the .Net version but with the Powershell version, even compiled programs depend on Powershell. Programs compiled with Powershell 2 (default on Windows 7) run only with Powershell 2. Programs compiled with Powershell 5 (default on Windows 10) run only with Powershell 3 or up. And there is nothing I can do about it.

Greetings

Markus

**Comment by MScholtes** [comment]
Close since no reaction for two months
